security:
    encoders:
        Boodcode\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:    ROLE_USER
        ROLE_SUPER_ADMIN:    [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: fos_userbundle
            form_login: 
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:    true
            remember_me:
                key:    %secret% #secret est un param de parameters.yml

    access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN, ip:[78.225.42.190,82.230.156.81] }
        #- { path: ^/register/, roles: ROLE_ADMIN, ip:[78.225.42.190,82.230.156.81] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }