<?php

namespace Boodcode\FranceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
	public function findImagesByWork($work_id)
	{
		$qb = $this
			->createQueryBuilder('i')
			->where("i.work = :id")
			->andWhere("i.url NOT LIKE '%home%'")
			->setParameter('id', $work_id);
		return $qb->getQuery()->getResult(); 

	}

}
