<?php

namespace Boodcode\FranceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkRepository extends EntityRepository
{
	public function findPublishedWorks()
	{
		$qb = $this
			->createQueryBuilder('w')
			->where("w.publication = 1")
			->orderBy('w.ordre', 'ASC');
		return $qb->getQuery()->getResult(); 

	}

	public function isFlood($ip, $secondes)
	{
	    $qb = $this->createQueryBuilder('w')
	               ->select('COUNT(w)')
	               ->where('w.ip = :ip')
	                 ->setParameter('ip', $ip)
	               ->andWhere('w.date >= :date')
	                 ->setParameter('date', new \Datetime('-'.$secondes.'seconds'));

	    return (bool) $qb->getQuery()->getSingleScalarResult();
	}
}
