<?php

namespace Proxies\__CG__\Boodcode\FranceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Work extends \Boodcode\FranceBundle\Entity\Work implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'id', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'titre', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'slug', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'description', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'details', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'publication', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'ordre', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'home_width', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'home_height', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'image');
        }

        return array('__isInitialized__', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'id', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'titre', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'slug', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'description', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'details', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'publication', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'ordre', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'home_width', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'home_height', '' . "\0" . 'Boodcode\\FranceBundle\\Entity\\Work' . "\0" . 'image');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Work $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function isDetailsValid(\Symfony\Component\Validator\Context\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDetailsValid', array($context));

        return parent::isDetailsValid($context);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetails($details)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetails', array($details));

        return parent::setDetails($details);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetails', array());

        return parent::getDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublication($publication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublication', array($publication));

        return parent::setPublication($publication);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublication', array());

        return parent::getPublication();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\Boodcode\FranceBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', array($image));

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\Boodcode\FranceBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', array($image));

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdre($ordre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdre', array($ordre));

        return parent::setOrdre($ordre);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdre', array());

        return parent::getOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomeWidth($homeWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomeWidth', array($homeWidth));

        return parent::setHomeWidth($homeWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomeWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomeWidth', array());

        return parent::getHomeWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomeHeight($homeHeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomeHeight', array($homeHeight));

        return parent::setHomeHeight($homeHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomeHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomeHeight', array());

        return parent::getHomeHeight();
    }

}
